<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="java_programs.LEVENSHTEIN_ESTest" tests="6" skipped="0" failures="1" errors="0" timestamp="2024-04-26T02:27:08" hostname="MacBook-Pro-685.local" time="0.029">
  <properties/>
  <testcase name="test0" classname="java_programs.LEVENSHTEIN_ESTest" time="0.008"/>
  <testcase name="test1" classname="java_programs.LEVENSHTEIN_ESTest" time="0.012"/>
  <testcase name="test2" classname="java_programs.LEVENSHTEIN_ESTest" time="0.003"/>
  <testcase name="test3" classname="java_programs.LEVENSHTEIN_ESTest" time="0.002">
    <failure message="java.lang.AssertionError: expected:&lt;0&gt; but was:&lt;3&gt;" type="java.lang.AssertionError">java.lang.AssertionError: expected:&lt;0&gt; but was:&lt;3&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at java_programs.LEVENSHTEIN_ESTest.test3(LEVENSHTEIN_ESTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
</failure>
  </testcase>
  <testcase name="test4" classname="java_programs.LEVENSHTEIN_ESTest" time="0.002"/>
  <testcase name="test5" classname="java_programs.LEVENSHTEIN_ESTest" time="0.002"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/eeeeeeshen/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-nop/1.7.32/e5349fc363dbc19c60cb12b10120b4c4f9e4aca8/slf4j-nop-1.7.32.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/eeeeeeshen/.gradle/caches/modules-2/files-2.1/org.evosuite/evosuite-master/1.0.6/14e9500b050a0816d5aec368e2391d99cbb53dee/evosuite-master-1.0.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.helpers.NOPLoggerFactory]
]]></system-err>
</testsuite>
