/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 04 21:39:09 GMT 2024
 */

package correct_java_programs;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import correct_java_programs.NEXT_PERMUTATION;
import java.util.ArrayList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NEXT_PERMUTATION_ESTest extends NEXT_PERMUTATION_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ArrayList<Integer> arrayList0 = new ArrayList<Integer>();
      Integer integer0 = Integer.getInteger("", 1);
      arrayList0.add(integer0);
      Integer integer1 = new Integer(1268);
      arrayList0.add(integer1);
      arrayList0.add(integer1);
      NEXT_PERMUTATION.next_permutation(arrayList0);
      assertEquals(3, arrayList0.size());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ArrayList<Integer> arrayList0 = new ArrayList<Integer>();
      Integer integer0 = Integer.getInteger("", 1);
      arrayList0.add(integer0);
      Integer integer1 = new Integer(1268);
      Integer integer2 = Integer.getInteger("CrVd!iJi", (-583));
      arrayList0.add(integer1);
      arrayList0.add(integer2);
      NEXT_PERMUTATION.next_permutation(arrayList0);
      assertEquals(3, arrayList0.size());
      assertTrue(arrayList0.contains(1));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ArrayList<Integer> arrayList0 = new ArrayList<Integer>();
      Integer integer0 = Integer.getInteger("", 1);
      arrayList0.add(integer0);
      arrayList0.add((Integer) null);
      // Undeclared exception!
      try { 
        NEXT_PERMUTATION.next_permutation(arrayList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("correct_java_programs.NEXT_PERMUTATION", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ArrayList<Integer> arrayList0 = new ArrayList<Integer>();
      Integer integer0 = Integer.getInteger("", 1);
      arrayList0.add(integer0);
      Integer integer1 = new Integer(1268);
      arrayList0.add(integer1);
      arrayList0.add(integer0);
      NEXT_PERMUTATION.next_permutation(arrayList0);
      assertEquals(3, arrayList0.size());
      assertTrue(arrayList0.contains(1268));
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ArrayList<Integer> arrayList0 = new ArrayList<Integer>();
      Integer integer0 = Integer.getInteger("", 1);
      arrayList0.add(integer0);
      arrayList0.add(integer0);
      ArrayList<Integer> arrayList1 = NEXT_PERMUTATION.next_permutation(arrayList0);
      assertNotSame(arrayList1, arrayList0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ArrayList<Integer> arrayList0 = new ArrayList<Integer>();
      // Undeclared exception!
      try { 
        NEXT_PERMUTATION.next_permutation(arrayList0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -2
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      NEXT_PERMUTATION nEXT_PERMUTATION0 = new NEXT_PERMUTATION();
  }
}
